[H]
coords = [[1.0, 0.0, 0.0]]
charges = [1]
charge = 0
spin = 1
tau = 0.1

["H2+"]
coords = [[-0.52918, 0.0, 0.0], [0.52918, 0.0, 0.0]]
charges = [1, 1]
charge = 1
spin = 1
tau = 0.1

[H2]
coords = [[0.0, 0.0, 0.0], [0.742, 0.0, 0.0]]
charges = [1, 1]
charge = 0
spin = 0
tau = 0.1

[Hn]
charge = 0
spin = 0
tau = 0.25

[Be]
coords = [[0.0, 0.0, 0.0]]
charges = [4]
charge = 0
spin = 0
tau = 0.08

[B]
coords = [[0.0, 0.0, 0.0]]
charges = [5]
charge = 0
spin = 1
tau = 0.05

[LiH]
coords = [[0.0, 0.0, 0.0], [1.595, 0.0, 0.0]]
charges = [3, 1]
charge = 0
spin = 0
tau = 0.15
