os: linux
dist: xenial
language: python
install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - echo VIRTUAL_ENV=$VIRTUAL_ENV
script:
  - poetry build
  - pip install deepqmc[wf,train,test] -f ./dist
  - coverage run -m pytest
after_success: bash <(curl -s https://codecov.io/bash)
jobs:
  include:
    - name: Style
      python: 3.7
      install:
        - pip install black flake8 flake8-bugbear flake8-comprehensions flake8-quotes pep8-naming isort pydocstyle
      script:
        - flake8
        - black . --check
        - isort . --check
        - pydocstyle src
    - python: 3.7
    - python: 3.8
    - name: Documentation
      python: 3.7
      install:
        - pip install sphinx sphinxcontrib-katex toml
      script:
        - sphinx-build -E doc doc/build
      workspaces:
        create:
          name: ws1
          paths:
            - doc/build
    - stage: deploy
      name: Documentation
      language: generic
      install: skip
      script: skip
      if: branch = master
      deploy:
        provider: pages
        skip_cleanup: true
        token: $GITHUB_TOKEN
        keep_history: true
        local_dir: doc/build
        repo: deepqmc/deepqmc.github.io
        target_branch: master
