[tool.poetry]
name = "dlqmc"
version = "0.1.0"
authors = [
    "Zeno Schätzle <zenoone@physik.fu-berlin.de>",
    "Jan Hermann <jan.hermann@fu-berlin.de>",
]
packages = [
    { include = "dlqmc", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
certifi = "*"
numpy = "^1.16"
torch = "~1.0"
scipy = "^1.2"
pyscf = "^1.6"
pandas = "^0.24.2"

[tool.poetry.dev-dependencies]
tqdm = "^4.31"
ipykernel = "^5.1"
matplotlib = "^3.0"
ipywidgets = "^7.4"
tensorboardX = "^1.6"
Pillow = "^5.4"
flake8 = "^3.5"
flake8-bugbear = "^18.8"
flake8-comprehensions = "^1.4"
flake8-quotes = "^1.0"
black = "^19-beta.0"
pep8-naming = "^0.7.0"
isort = "^4.3"
pytest = "^4.4"
nbstripout = "^0.3.5"
pysnooper = "^0.0.12"


[tool.black]
py36 = true
skip-string-normalization = true
skip-numeric-underscore-normalization = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

