[tool.poetry]
name = "deepqmc"
version = "0.1.0"
description = "Deep-learning quantum Monte Carlo"
authors = [
    "Jan Hermann <jan.hermann@fu-berlin.de>",
    "Zeno Schätzle <zenoone@physik.fu-berlin.de>",
]
packages = [
    { include = "deepqmc", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
certifi = "*"
numpy = "^1.16"
torch = "^1.1"
scipy = "^1.2"
pyscf = "^1.6"
pandas = "^0.24.2"
toml = "^0.10.0"
pytest = { version = "^4.4", optional = true }
tensorboard = { version = "^2.0", optional = true }
tqdm = { version = "^4.31", optional = true }
click = { version = "^7.0", optional = true }
importlib-metadata = { version = "^0.23.0", optional = true }
sphinx = { version = "^2.2", optional = true }
coverage = { version = "^4.5",optional = true }

[tool.poetry.extras]
test = ["pytest", "coverage"]
doc = ["sphinx"]
train = ["tensorboard", "tqdm", "click", "importlib-metadata"]

[tool.poetry.dev-dependencies]
flake8 = "^3.5"
flake8-bugbear = "^18.8"
flake8-comprehensions = "^1.4"
flake8-quotes = "^1.0"
black = "^19-beta.0"
pep8-naming = "^0.7.0"
isort = "^4.3"

[tool.poetry.scripts]
deepqmc-train = "deepqmc.train:train_from_file"

[tool.black]
target-version = ["py37"]
skip-string-normalization = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
